// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCz0ms9sJwEj2Tp-Q9Mvy3JKtnOLXb8sY8',
    appId: '1:207978312436:web:1faaa2eea6bf3d2158e4a1',
    messagingSenderId: '207978312436',
    projectId: 'chatty-box-c5acc',
    authDomain: 'chatty-box-c5acc.firebaseapp.com',
    storageBucket: 'chatty-box-c5acc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCz4LDR8j5eDRJdwEifdxny6z_LdWQnumI',
    appId: '1:207978312436:android:134452157a24bfcc58e4a1',
    messagingSenderId: '207978312436',
    projectId: 'chatty-box-c5acc',
    storageBucket: 'chatty-box-c5acc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCx5U2QumRhu4RJ0iyvTbU1VX4YYnFG3Ao',
    appId: '1:207978312436:ios:652657705e8e871058e4a1',
    messagingSenderId: '207978312436',
    projectId: 'chatty-box-c5acc',
    storageBucket: 'chatty-box-c5acc.appspot.com',
    androidClientId: '207978312436-av9f96sm9ed8kka83cd4urdrqc8pamcu.apps.googleusercontent.com',
    iosClientId: '207978312436-e4bk1am9jp5jdoecqpiu7dl6p4jrll0b.apps.googleusercontent.com',
    iosBundleId: 'com.example.chattyBox',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCx5U2QumRhu4RJ0iyvTbU1VX4YYnFG3Ao',
    appId: '1:207978312436:ios:12cac97b68ef04c658e4a1',
    messagingSenderId: '207978312436',
    projectId: 'chatty-box-c5acc',
    storageBucket: 'chatty-box-c5acc.appspot.com',
    androidClientId: '207978312436-av9f96sm9ed8kka83cd4urdrqc8pamcu.apps.googleusercontent.com',
    iosClientId: '207978312436-qp2i5kqbjoajivssvck057bugdup2phv.apps.googleusercontent.com',
    iosBundleId: 'com.example.chattyBox.RunnerTests',
  );
}
